src/java/com/moduleBackLine/bean/InventoryItem.java
package com.moduleBackLine.bean;

public class InventoryItem {
    // slock number
    int stock;
    // model or type of inventory
    String model;
    // description of item
    String description;
    // number of miles on odometer
    int odometer;
    // price of car in Canadian dollars
    int price;

    /**
     * Creates a new instance of InventoryItem.
     * @param stock stock number.
     * @param model model or type of inventory.
     * @param description description of item.
     * @param odometer number of miles on odometer.
     * @param price price of care in Canadian dollars.
     */
    public InventoryItem(int stock, String model, String description, int odometer, int price) {
        this.stock = stock;
        this.model = model;
        this.description = description;
        this.odometer = odometer;
        this.price = price;
    }

    /**
     * Gets the stock number of this iventory item.
     * @return stock number.
     */
    public int getStock() {
        return stock;
    }

    /**
     * Gets the model number of this iventory item.
     * @return model number.
     */
    public String getModel() {
        return model;
    }

    /**
     * Gets the description of the this iventory item.
     * @return description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Gets the odometer reading from this iventory item.
     * @return  odometer reading.
     */
    public int getOdometer() {
        return odometer;
    }

    /**
     * Gets the price of this item in Canadian Dollars.
     * @return price.
     */
    public int getPrice() {
        return price;
    }

}

src/java/com/moduleBackLine/bean/assembly/assemblyControl.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moduleBackLine.bean.assembly;

import com.appCinfigpage.bean.userLogin;
import com.moduleBackLine.Dataworksheet.blBarcode;
import com.moduleBackLine.Dataworksheet.workSheetDetail;
import com.moduleBackLine.bean.printassyworksheet;
import com.moduleFontline.DataWorksheet.detailProcess;
import com.tct.barcodegenerate.BarCodeGenerter;
import com.tct.data.*;
import com.tct.data.jpa.*;
import com.tct.data.jpa.exceptions.NonexistentEntityException;
import com.tct.data.jsf.util.PaginationHelper;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.Persistence;

/**
 *
 * @author The_Boy_Cs
 */
public class assemblyControl {
//======= Search =====================================

    private String modelsearch;
    private String barcodesearch;
    private String seriessearch;
    private String processsearch;
//====================================================
    private DataModel worksheet;
    private List<workSheetDetail> worksheetlist;
    private List<LineAssembly> detailAssemblys;
    private Details currentdetails;
    private List<LotControl> lotControllist;
    private ModelPool currentModelPool;
    private List<ModelPool> modelPoolslist;
    private List<String> modelPools;
    private LotControl currentlotControl = null;
    private LineAssembly currentdetailassembly;
    private List<SelectItem> modelpoollist;
    private List<detailProcess> detailprocess;
    private List<SelectItem> productcodename = null;
    private List<SelectItem> producttype = null;
    // new combobox
    private List<SelectItem> inklist = null;
    private List<SelectItem> solderlist = null;
    private List<SelectItem> potcorelist = null;
    private List<SelectItem> bondlist = null;
    // end----------------

    public assemblyControl() {
        searchAssemblyWorksheet();
    }

    public void create(ActionEvent event) {
        print("==================== Create =====================================");
        printassyworksheet.barcode = null;
        printassyworksheet.detail = null;
        currentlotControl = null;
        try {
            Users user = userLogin.getSessionUser();
            getCurrentdetails().setIdDetail(UUID.randomUUID().toString());
            getCurrentdetails().setDateCreate(new Date());
            getCurrentdetails().setDeleted(0);
            getCurrentdetails().setDetailName("line_assembly");
            getCurrentdetails().setDetailType("backline");
            getCurrentdetails().setUserCreate(user.getId());
//            getCurrentdetails().set

            getCurrentdetailassembly().setDetailIdDetail(getCurrentdetails());
            getCurrentdetailassembly().setId(UUID.randomUUID().toString());
            getCurrentdetailassembly().setDetailproductreport("");

            getDetailsJpaController().create(getCurrentdetails());
            getLineAssemblyJpaController().create(getCurrentdetailassembly());

            int lot = Integer.parseInt(getCurrentdetails().getLotcontrol());
            String partfile = FacesContext.getCurrentInstance().getExternalContext().getRealPath("/images/barcode/");
            print(" PartFile : " + partfile);

            for (int i = 0; i < lot; i++) {
                int maxnum = getBarcodeGenerater().getMaxnumberOfLotcontrol() + 1;
                String barcode = "BSB" + getCurrentdetailassembly().getPdCode() + getCurrentdetailassembly().getPdType() + "-"
                        + new SimpleDateFormat("MMyy").format(new Date()) + currentModelPool.getModelSeries() + maxnum;

                getCurrentlotControl().setId(UUID.randomUUID().toString());
                getCurrentlotControl().setBarcode(barcode);
                getCurrentlotControl().setDeleted(0);
                getCurrentlotControl().setDetailsIdDetail(getCurrentdetails());
                getCurrentlotControl().setLotNumber((1+i) + "");
                getCurrentlotControl().setModelPoolId(getCurrentModelPool());

                if (genBarCode(barcode, partfile)) {
                    getLotControlJpaController().create(getCurrentlotControl());
                    getBarcodelist().add(new blBarcode(getCurrentlotControl().getId(), barcode, "./images/barcode/", true));
                    print("= Barcode : " + barcode);
                    getBarcodeGenerater().updateMaxnumberOfLotcontrol(maxnum);
                }
                print("= Insert Lotcontrol : " + currentlotControl);
            }
            printassyworksheet.detail = currentdetails;
            Thread.sleep(1000);
            String link = "pages/moduleBackLine/assembly/printview.xhtml";
            userLogin.getSessionMenuBarBean().setParam(link);
            searchAssemblyWorksheet();
        } catch (Exception e) {
            print("= Error : " + e);
        }
    }

    private List<blBarcode> getBarcodelist() {
        if (printassyworksheet.barcode == null) {
            printassyworksheet.barcode = new ArrayList<blBarcode>();
        }
        return printassyworksheet.barcode;
    }

    private boolean genBarCode(String code, String filePath) {
        print("===================== genbarcode file ===========================");
        try {
            getBarcodeGenerater().createBarcode(code, filePath + "/1d/");
            getBarcodeGenerater().createQrCode(code, filePath + "/2d/");
            print("= GenCode : Complete");
            return true;
        } catch (Exception e) {
            print("= Error can not genbarcode." + e.toString());
            return false;
        }
    }

    public void changProductTypevalue(ValueChangeEvent event) {
        print("=================== Product type ================================");
        String pdType = event.getNewValue().toString();
        getCurrentdetailassembly().setPdType(pdType);
        print("= PdType : " + getCurrentdetailassembly().getPdType());
    }

    public void changProductcodeName(ValueChangeEvent event) {
        print("================== Productcode Chang ============================");
        String pdcodename = event.getNewValue().toString();
        String pd_code = null;
        try {
            if (pdcodename.equals("Prototype")) {
                pd_code = "P";
            } else if (pdcodename.equals("New product introduction")) {
                pd_code = "N";
            } else if (pdcodename.equals("Special built request")) {
                pd_code = "S";
            } else if (pdcodename.equals("Mass production")) {
                pd_code = "M";
            }
            getCurrentdetailassembly().setPdCodeName(pdcodename);
            getCurrentdetailassembly().setPdCode(pd_code);
        } catch (Exception e) {
            print("= Error : " + e);
        }
        print("= Product name : " + event.getNewValue());
        print("= Product Code : " + pd_code);
    }

    public void changModelseriesValue(ValueChangeEvent event) {
        print("================== Series chang value ===========================");
        modelpoollist = null;
        detailprocess = null;
        try {
            String series = event.getNewValue().toString();
            print("= series : " + series);
            modelPoolslist = getModelPoolJpaController().findModelPoolBySeries(series);
            for (ModelPool modelPool : modelPoolslist) {
                getModelpoollist().add(new SelectItem(modelPool.getId(), modelPool.getModelName()));
            }
        } catch (Exception e) {
            print("= Error : " + e);
        }
    }

    public void changModelValue(ValueChangeEvent event) {
        print("================== Model chang value ============================");
        String modelId = event.getNewValue().toString();
        print(" ModelId : " + modelId);
        try {
            currentModelPool = getModelPoolJpaController().findModelPool(modelId);
            print("Modelpool : " + currentModelPool);
            getCurrentdetails().setModel(modelId);
            List<Md2pc> md2pcs = getMd2pcJpaController().findBymodelPoolId(currentModelPool);
            for (Md2pc md2pc : md2pcs) {
                getDetailprocess().add(new detailProcess(md2pc.getProcessPoolIdProc().getCodeOperation(), null, null, null, null, "", md2pc.getProcessPoolIdProc().getProcName(), "", 0, 0, 0, "", ""));
            }
        } catch (Exception e) {
            print("= Error : " + e);
        }
    }

    public List<SelectItem> getModelserieslist() {
        print("================= getModelserieslist ============================");
        try {
            modelPools = getModelPoolJpaController().findModelPoolGroupBySeries();
            List<SelectItem> seriesList = new ArrayList<SelectItem>();
            for (String series : modelPools) {
                seriesList.add(new SelectItem(series, series));
            }
            return seriesList;
        } catch (Exception e) {
            print("= Error : " + e);
            return null;
        }
    }

    public Details getCurrentdetails() {
        if (currentdetails == null) {
            currentdetails = new Details();
        }
        return currentdetails;
    }

    public LineAssembly getCurrentdetailassembly() {
        if (currentdetailassembly == null) {
            currentdetailassembly = new LineAssembly();
        }
        return currentdetailassembly;
    }

    public void searchAssemblyWorksheet() {
        print("==================== Search worksheet Assembly ==================");
        try {
            if (barcodesearch != null && !barcodesearch.trim().isEmpty()) {

src/java/com/moduleBackLine/bean/list/view.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moduleBackLine.bean.list;

/**
 *
 * @author The_Boy_Cs
 */
public class view {
    
}

web/pages/moduleBackLine/newcreate/createview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:icecore="http://www.icefaces.org/icefaces/core"
      xmlns:ace="http://www.icefaces.org/icefaces/components"
      xmlns:ice="http://www.icesoft.com/icefaces/component">
    <h:head>
        <title>New create</title>
        <link rel="stylesheet" type="text/css"
              href="../../xmlhttp/css/rime/rime.css" />
        <link rel="stylesheet" type="text/css" href="../css/layout.css"/> 
    </h:head>
    <h:body>
        <!--Create Worksheet-->
        <div class="box">
            <ice:form>
                <div class="heading">
                    <h1><img src="../images/h1_refu.png" />New Create</h1>
                    <div class="buttons">
                        <ice:commandButton partialSubmit="true" styleClass="button_create" value="Create" actionListener="#{newcreatecontrol.create}" />
                        <ice:commandButton partialSubmit="true" styleClass="button_cancel" value="Cancel" actionListener="#{newcreatecontrol.changToCancel}"/>
                    </div>
                </div>
                <div class="content">
                    <table class="form">
                        <tr>
                            <td class="label">Lot Control :</td>
                            <td ><ice:inputText value="#{newcreatecontrol.currentdetails.lotcontrol}">
                                    <f:convertNumber integerOnly="true"/>
                                </ice:inputText></td>
                            <td class="label">Type :</td>
                            <td>
                                <ice:selectOneMenu value="#{newcreatecontrol.currentRefu01.type}" partialSubmit="true">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.typelist}"/>
                                </ice:selectOneMenu>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">Series :</td>
                            <td>
                                <ice:selectOneMenu partialSubmit="true" value="#{newcreatecontrol.currentdetails.modelseries}" required="true" requiredMessage="Select this." valueChangeListener="#{newcreatecontrol.changModelseriesValue}">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.modelserieslist}"/>
                                </ice:selectOneMenu>
                            </td>
                            <td class="label">Stamp :</td>
                            <td ><ice:inputText value="#{newcreatecontrol.currentRefu01.stamp}"/></td>
                        </tr>
                        <tr>
                            <td class="label">Model :</td>
                            <td>
                                <ice:selectOneMenu partialSubmit="true" value="#{newcreatecontrol.currentdetails.model}" required="true" requiredMessage="Select this." valueChangeListener="#{newcreatecontrol.changModelValue}">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.modelpoollist}"/>
                                </ice:selectOneMenu>
                            </td>
                            <td class="label">Line :</td>
                            <td>
                                <ice:inputText value="#{newcreatecontrol.currentdetails.line}"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">L1</td>
                            <td><ice:inputText value="#{newcreatecontrol.currentRefu01.l1}"/></td>
                            <td class="label">L2</td>
                            <td><ice:inputText value="#{newcreatecontrol.currentRefu01.l2}"/></td>
                        </tr>
                    </table>
                </div>
            </ice:form>
            <!-- Process Status -->
            <h2 class="lable_line">Process Status (#{newcreatecontrol.detailprocess.size()}) </h2>
            <div  class="content_line">
                <div class="content_process">
                    <table width="100%" class="xxtable" cellspacing="0" cellpadding="0">
                        <tr>
                            <td class="process_lable" width="20%" >Process</td>
                            <td class="process_lable" width="2%" > Shift </td>
                            <td class="process_lable" width="12%" > M/C </td>
                            <td class="process_lable" width="13%" > Start <br />Date/Time </td>
                            <td class="process_lable" width="13%" > Finish <br /> Date/Time </td>
                            <td class="process_lable" width="5%" > Before <br />WIP I/P</td>
                            <td class="process_lable" width="5%" > After <br />  WIP O/P </td>
                            <td class="process_lable" width="5%" > Input </td>
                            <td class="process_lable" width="5%" > NG </td>
                            <td class="process_lable" width="5%" > Repair </td>
                            <td class="process_lable" width="5%" > Output </td>	
                            <td class="process_lable" width="5%" > %NG </td>
                            <td class="process_lable" width="5%" > %Repair </td>
                        </tr>
                    </table>
                    <ice:panelSeries var="detailprocess" value="#{newcreatecontrol.detailprocess}">
                        <table width="100%" class="xxtable" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="process_td" width="20%" align="center"><b>#{detailprocess.processname}</b></td>
                                <td class="process_td" width="2%" align="center">-</td>
                                <td class="process_td" width="12%" align="center">-</td>
                                <td class="process_td" width="13%" align="center">-</td>
                                <td class="process_td" width="13%" align="center">-</td>
                                <td class="process_td" width="5%" align="right">-</td>
                                <td class="process_td" width="5%" align="right">-</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0.00%</td>
                                <td class="process_td" width="5%" align="right">0.00%</td>
                            </tr>
                        </table>
                    </ice:panelSeries>
                </div>
            </div>
            <!--end Process Status -->
        </div>  
    </h:body>
</html>

web/pages/moduleBackLine/newcreate/detailview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

web/pages/moduleBackLine/newcreate/editview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:icecore="http://www.icefaces.org/icefaces/core"
      xmlns:ace="http://www.icefaces.org/icefaces/components"
      xmlns:ice="http://www.icesoft.com/icefaces/component">
    <h:head>
        <title>New create</title>
        <link rel="stylesheet" type="text/css"
              href="../../xmlhttp/css/rime/rime.css" />
        <link rel="stylesheet" type="text/css" href="../css/layout.css"/> 
    </h:head>
    <h:body>
        <!--Create Worksheet-->
        <div class="box">
            <ice:form>
                <div class="heading">
                    <h1><img src="../images/h1_refu.png" />Edit New Create</h1>
                    <div class="buttons">
                        <ice:commandButton partialSubmit="true" styleClass="button_create" value="Save" actionListener="#{newcreatecontrol.changToSave}" />
                        <ice:commandButton partialSubmit="true" styleClass="button_cancel" value="Cancel" actionListener="#{newcreatecontrol.changToCancel}"/>
                        <ice:commandButton panelConfirmation="confirmdeletedetail" styleClass="button_delete" partialSubmit="true" value="Delete" actionListener="#{newcreatecontrol.changTodelAll}"/>
                        <ice:panelConfirmation id="confirmdeletedetail" acceptLabel="Confirm" cancelLabel="Cancel" title="Confirm delete" message="You are about to delete. Are you sure?" draggable="false" autoCentre="true" rendered="true"/>
                    </div>
                </div>
                <div class="content">
                    <table class="form">
                        <tr>
                            <td class="label">Lot Control :</td>
                            <td ><ice:inputText readonly="true" value="#{newcreatecontrol.currentdetails.lotcontrol}">
                                    <f:convertNumber integerOnly="true"/>
                                </ice:inputText></td>
                            <td class="label">Type :</td>
                            <td>
                                <ice:selectOneMenu value="#{newcreatecontrol.currentRefu01.type}" partialSubmit="true">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.typelist}"/>
                                </ice:selectOneMenu>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">Series :</td>
                            <td>
                                <ice:selectOneMenu partialSubmit="true" value="#{newcreatecontrol.currentdetails.modelseries}" required="true" requiredMessage="Select this." valueChangeListener="#{newcreatecontrol.changModelseriesValue}">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.modelserieslist}"/>
                                </ice:selectOneMenu>
                            </td>
                            <td class="label">Stamp :</td>
                            <td ><ice:inputText value="#{newcreatecontrol.currentRefu01.stamp}"/></td>
                        </tr>
                        <tr>
                            <td class="label">Model :</td>
                            <td>
                                <ice:selectOneMenu partialSubmit="true" value="#{newcreatecontrol.currentdetails.model}" required="true" requiredMessage="Select this." valueChangeListener="#{newcreatecontrol.changModelValue}">
                                    <f:selectItem itemValue="" itemLabel="----- Select One -----"/>
                                    <f:selectItems value="#{newcreatecontrol.modelpoollist}"/>
                                </ice:selectOneMenu>
                            </td>
                            <td class="label">Line :</td>
                            <td>
                                <ice:inputText value="#{newcreatecontrol.currentdetails.line}"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">L1</td>
                            <td><ice:inputText value="#{newcreatecontrol.currentRefu01.l1}"/></td>
                            <td class="label">L2</td>
                            <td><ice:inputText value="#{newcreatecontrol.currentRefu01.l2}"/></td>
                        </tr>
                    </table>
                </div>
            </ice:form>
            <!-- Process Status -->
            <h2 class="lable_line">Process Status (#{newcreatecontrol.detailprocess.size()}) </h2>
            <div  class="content_line">
                <div class="content_process">
                    <table width="100%" class="xxtable" cellspacing="0" cellpadding="0">
                        <tr>
                            <td class="process_lable" width="20%" >Process</td>
                            <td class="process_lable" width="2%" > Shift </td>
                            <td class="process_lable" width="12%" > M/C </td>
                            <td class="process_lable" width="13%" > Start <br />Date/Time </td>
                            <td class="process_lable" width="13%" > Finish <br /> Date/Time </td>
                            <td class="process_lable" width="5%" > Before <br />WIP I/P</td>
                            <td class="process_lable" width="5%" > After <br />  WIP O/P </td>
                            <td class="process_lable" width="5%" > Input </td>
                            <td class="process_lable" width="5%" > NG </td>
                            <td class="process_lable" width="5%" > Repair </td>
                            <td class="process_lable" width="5%" > Output </td>	
                            <td class="process_lable" width="5%" > %NG </td>
                            <td class="process_lable" width="5%" > %Repair </td>
                        </tr>
                    </table>
                    <ice:panelSeries var="detailprocess" value="#{newcreatecontrol.detailprocess}">
                        <table width="100%" class="xxtable" cellspacing="0" cellpadding="0">
                            <tr>
                                <td class="process_td" width="20%" align="center"><b>#{detailprocess.processname}</b></td>
                                <td class="process_td" width="2%" align="center">-</td>
                                <td class="process_td" width="12%" align="center">-</td>
                                <td class="process_td" width="13%" align="center">-</td>
                                <td class="process_td" width="13%" align="center">-</td>
                                <td class="process_td" width="5%" align="right">-</td>
                                <td class="process_td" width="5%" align="right">-</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0</td>
                                <td class="process_td" width="5%" align="right">0.00%</td>
                                <td class="process_td" width="5%" align="right">0.00%</td>
                            </tr>
                        </table>
                    </ice:panelSeries>
                </div>
            </div>
            <!--end Process Status -->
        </div>  
    </h:body>
</html>