src/java/com/moduleBackLine/bean/list/view.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moduleBackLine.bean.list;

/**
 *
 * @author The_Boy_Cs
 */
public class view {
    
}

src/java/com/tct/data/jsf/PcsQtyController.java
package com.tct.data.jsf;

import com.tct.data.PcsQty;
import com.tct.data.jsf.util.JsfUtil;
import com.tct.data.jsf.util.PaginationHelper;
import com.tct.data.jpa.PcsQtyJpaController;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.Persistence;

@ManagedBean(name = "pcsQtyController")
@SessionScoped
public class PcsQtyController implements Serializable {

    private PcsQty current;
    private DataModel items = null;
    private PcsQtyJpaController jpaController = null;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PcsQtyController() {
    }

    public PcsQty getSelected() {
        if (current == null) {
            current = new PcsQty();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PcsQtyJpaController getJpaController() {
        if (jpaController == null) {
            jpaController = new PcsQtyJpaController(Persistence.createEntityManagerFactory("tct_projectxPU"));
        }
        return jpaController;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getJpaController().getPcsQtyCount();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getJpaController().findPcsQtyEntities(getPageSize(), getPageFirstItem()));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (PcsQty) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new PcsQty();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getJpaController().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PcsQtyCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (PcsQty) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getJpaController().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PcsQtyUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (PcsQty) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getJpaController().destroy(current.getId());
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PcsQtyDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getJpaController().getPcsQtyCount();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getJpaController().findPcsQtyEntities(1, selectedItemIndex).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(getJpaController().findPcsQtyEntities(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(getJpaController().findPcsQtyEntities(), true);
    }

    @FacesConverter(forClass = PcsQty.class)
    public static class PcsQtyControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PcsQtyController controller = (PcsQtyController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pcsQtyController");
            return controller.getJpaController().findPcsQty(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof PcsQty) {
                PcsQty o = (PcsQty) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + PcsQtyController.class.getName());
            }
        }
    }
}

web/pagenerate/pcsQty/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePcsQtyTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePcsQtyLabel_id}" for="id" />
                    <h:inputText id="id" value="#{pcsQtyController.selected.id}" title="#{bundle.CreatePcsQtyTitle_id}" required="true" requiredMessage="#{bundle.CreatePcsQtyRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreatePcsQtyLabel_qtyType}" for="qtyType" />
                    <h:inputText id="qtyType" value="#{pcsQtyController.selected.qtyType}" title="#{bundle.CreatePcsQtyTitle_qtyType}" />
                    <h:outputLabel value="#{bundle.CreatePcsQtyLabel_qty}" for="qty" />
                    <h:inputText id="qty" value="#{pcsQtyController.selected.qty}" title="#{bundle.CreatePcsQtyTitle_qty}" />
                    <h:outputLabel value="#{bundle.CreatePcsQtyLabel_currentProcessId}" for="currentProcessId" />
                    <h:selectOneMenu id="currentProcessId" value="#{pcsQtyController.selected.currentProcessId}" title="#{bundle.CreatePcsQtyTitle_currentProcessId}" required="true" requiredMessage="#{bundle.CreatePcsQtyRequiredMessage_currentProcessId}">
                        <f:selectItems value="#{currentProcessController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pcsQtyController.create}" value="#{bundle.CreatePcsQtySaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{pcsQtyController.prepareList}" value="#{bundle.CreatePcsQtyShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.CreatePcsQtyIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pagenerate/pcsQty/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPcsQtyTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPcsQtyLabel_id}" for="id" />
                    <h:inputText id="id" value="#{pcsQtyController.selected.id}" title="#{bundle.EditPcsQtyTitle_id}" required="true" requiredMessage="#{bundle.EditPcsQtyRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditPcsQtyLabel_qtyType}" for="qtyType" />
                    <h:inputText id="qtyType" value="#{pcsQtyController.selected.qtyType}" title="#{bundle.EditPcsQtyTitle_qtyType}" />
                    <h:outputLabel value="#{bundle.EditPcsQtyLabel_qty}" for="qty" />
                    <h:inputText id="qty" value="#{pcsQtyController.selected.qty}" title="#{bundle.EditPcsQtyTitle_qty}" />
                    <h:outputLabel value="#{bundle.EditPcsQtyLabel_currentProcessId}" for="currentProcessId" />
                    <h:selectOneMenu id="currentProcessId" value="#{pcsQtyController.selected.currentProcessId}" title="#{bundle.EditPcsQtyTitle_currentProcessId}" required="true" requiredMessage="#{bundle.EditPcsQtyRequiredMessage_currentProcessId}">
                        <f:selectItems value="#{currentProcessController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{pcsQtyController.update}" value="#{bundle.EditPcsQtySaveLink}"/>
                <br />
                <br />
                <h:commandLink action="View" value="#{bundle.EditPcsQtyViewLink}" immediate="true"/>
                <br />
                <h:commandLink action="#{pcsQtyController.prepareList}" value="#{bundle.EditPcsQtyShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.EditPcsQtyIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pagenerate/pcsQty/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPcsQtyTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPcsQtyEmpty}" rendered="#{pcsQtyController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{pcsQtyController.items.rowCount > 0}">
                    <h:outputText value="#{pcsQtyController.pagination.pageFirstItem + 1}..#{pcsQtyController.pagination.pageLastItem + 1}/#{pcsQtyController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{pcsQtyController.previous}" value="#{bundle.Previous} #{pcsQtyController.pagination.pageSize}" rendered="#{pcsQtyController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{pcsQtyController.next}" value="#{bundle.Next} #{pcsQtyController.pagination.pageSize}" rendered="#{pcsQtyController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{pcsQtyController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPcsQtyTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPcsQtyTitle_qtyType}"/>
                            </f:facet>
                            <h:outputText value="#{item.qtyType}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPcsQtyTitle_qty}"/>
                            </f:facet>
                            <h:outputText value="#{item.qty}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPcsQtyTitle_currentProcessId}"/>
                            </f:facet>
                            <h:outputText value="#{item.currentProcessId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{pcsQtyController.prepareView}" value="#{bundle.ListPcsQtyViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pcsQtyController.prepareEdit}" value="#{bundle.ListPcsQtyEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pcsQtyController.destroy}" value="#{bundle.ListPcsQtyDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{pcsQtyController.prepareCreate}" value="#{bundle.ListPcsQtyCreateLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ListPcsQtyIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pagenerate/pcsQty/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPcsQtyTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPcsQtyLabel_id}"/>
                    <h:outputText value="#{pcsQtyController.selected.id}" title="#{bundle.ViewPcsQtyTitle_id}"/>
                    <h:outputText value="#{bundle.ViewPcsQtyLabel_qtyType}"/>
                    <h:outputText value="#{pcsQtyController.selected.qtyType}" title="#{bundle.ViewPcsQtyTitle_qtyType}"/>
                    <h:outputText value="#{bundle.ViewPcsQtyLabel_qty}"/>
                    <h:outputText value="#{pcsQtyController.selected.qty}" title="#{bundle.ViewPcsQtyTitle_qty}"/>
                    <h:outputText value="#{bundle.ViewPcsQtyLabel_currentProcessId}"/>
                    <h:outputText value="#{pcsQtyController.selected.currentProcessId}" title="#{bundle.ViewPcsQtyTitle_currentProcessId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pcsQtyController.destroyAndView}" value="#{bundle.ViewPcsQtyDestroyLink}"/>
                <br />
                <br />
                <h:commandLink action="Edit" value="#{bundle.ViewPcsQtyEditLink}"/>
                <br />
                <h:commandLink action="#{pcsQtyController.prepareCreate}" value="#{bundle.ViewPcsQtyCreateLink}" />
                <br />
                <h:commandLink action="#{pcsQtyController.prepareList}" value="#{bundle.ViewPcsQtyShowAllLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ViewPcsQtyIndexLink}" action="/index" immediate="true" />

            </h:form>
        </ui:define>
    </ui:composition>

</html>