src/java/com/moduleBackLine/bean/list/view.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moduleBackLine.bean.list;

/**
 *
 * @author The_Boy_Cs
 */
public class view {
    
}

src/java/com/setting/bean/editngControl.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.setting.bean; 

import com.appCinfigpage.bean.fc;
import com.appCinfigpage.bean.userLogin;
import com.setting.DataProcess.NGPool;
import com.setting.Dataworksheet.editngDetail;
import com.tct.data.NgPool;
import java.util.ArrayList;
import java.util.List;
import com.tct.data.Pc2ng;
import com.tct.data.jpa.NgPoolJpaController; 
import com.tct.data.jsf.util.PaginationHelper;
import com.time.timeCurrent;
import java.awt.event.ActionEvent;
import java.util.UUID;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.Persistence; 
/**
 *
 * Machine User @author pang
 * Development by Chusak laojang
 * Date : Sep 6, 2012, Time : 10:20:44 AM 
 * Copy Right 4 Xtreme Co.,Ltd.
 */
public class editngControl {
    private List<editngDetail>  editngcontrolData;
    private NgPoolJpaController  ngPoolJpaController  = null;
    private List<NgPool>         itemPc2ng = null;   
    private DataModel worksheet; 
    private PaginationHelper worksheetpagination;
    private List<SelectItem>   itemNgType ; 
    private List<SelectItem>   itemNgStatus;
    private String  ngNameSearch;
    private String  ngCodeSearch;
    private String  ngTypeSearch;
    private String  ngStatusSearch;
    private NgPool  currentPool;
    
    public editngControl() {
        searchEditngList();
        loadItemNgType();
        loadItemNgStatus();
    }
    private  NgPoolJpaController  getNgPoolJpaController()
    {
        if(ngPoolJpaController == null)
        {
            ngPoolJpaController  = new  NgPoolJpaController(Persistence.createEntityManagerFactory("tct_projectxPU"));
        }
        return ngPoolJpaController;
    }
    public List<editngDetail> getEditngcontrolData() {
        if(editngcontrolData  == null)
        {
            editngcontrolData  = new ArrayList<editngDetail>();
        }
        return editngcontrolData;
    }
    public  void changeToInsert()
    {  
        currentPool  = null;
        editngcontrolData  = null;
        itemPc2ng    = null;
        String link  = "pages/setting/editng/createview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link); 
    }
    public void changeToSave()
    {
        getCurrentPool().setNgCode(currentPool.getNgCode());
        getCurrentPool().setNgName(currentPool.getNgName());
        getCurrentPool().setStatus(currentPool.getStatus());
        getCurrentPool().setNgType(currentPool.getNgType());
        try
        {
            getNgPoolJpaController().edit(getCurrentPool());
        }
        catch(Exception e)
        {
            fc.print("Error not changeToSave"+e);
        }
        loadSearchEditListAll(); 
        String link = "pages/setting/editng/listview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link); 
    }
    public void changeToEdit(String index)
    { 
        currentPool  = null;
        itemPc2ng    = null;
        //editngDetail  editdetail  = (editngDetail)  worksheet.getRowData();
        currentPool  = getNgPoolJpaController().findNgPool(index);
        String link = "pages/setting/editng/editview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link); 
    }
    public void changToDelete(String index)
    {
        currentPool  = null;
        itemPc2ng    = null;
        currentPool  = getNgPoolJpaController().findNgPool(index);
        getCurrentPool().setDeleted(1);
        try
        {
            getNgPoolJpaController().edit(getCurrentPool());
        }
        catch(Exception e)
        {
            fc.print("Error"+e);
        }
        String link = "pages/setting/editng/listview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link); 
        loadSearchEditListAll(); 
    }        
    public void changeToCreate()
    {
        String  idngNew  = UUID.randomUUID().toString();
        getCurrentPool().setIdNg(idngNew);
        getCurrentPool().setNgCode(currentPool.getNgCode());
        getCurrentPool().setNgName(currentPool.getNgName());
        getCurrentPool().setStatus(currentPool.getStatus());
        getCurrentPool().setCreateDate(new timeCurrent().getDate());
        getCurrentPool().setUserCreate(userLogin.getSessionUser().getUserName());
        getCurrentPool().setUserApprove("");
        getCurrentPool().setUserModifire("");
        getCurrentPool().setDateModifire(new timeCurrent().getDate());
        try{
            getNgPoolJpaController().create(getCurrentPool());
            fc.print("======== Insert new ng ========");
        }
        catch(Exception e )
        {
            fc.print("Eror "+e);
        }
        String link = "pages/setting/editng/listview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link);  
        currentPool  = null;
        editngcontrolData  = null;
        itemPc2ng    = null;
        loadSearchEditListAll();
    } 
    public void changeToCancel()
    {
        String link = "pages/setting/editng/listview.xhtml";
        userLogin.getSessionMenuBarBean().setParam(link); 
    }
    
    private void loadSearchEditListAll() {
         editngcontrolData  = null;
         itemPc2ng  = null;
         itemPc2ng  = getNgPoolJpaController().findByNotdeleted();
         for(NgPool itempc2ndg : itemPc2ng)
         {
             getEditngcontrolData().add(new editngDetail(itempc2ndg.getIdNg(),itempc2ndg.getNgCode(),itempc2ndg.getNgName(), itempc2ndg.getNgType(),itempc2ndg.getStatus(),itempc2ndg.getCreateDate().toString(), itempc2ndg.getUserCreate(),null, null));
             fc.print(itempc2ndg.getNgCode());
         }
         setWorksheet();
     }
     public void previous() {
        getWorksheetpagination().previousPage();
        setWorksheet();
    }

    public void next() {
        getWorksheetpagination().nextPage();
        setWorksheet();
    }

    public int getAllPages() {
        int all = getWorksheetpagination().getItemsCount();
        int pagesize = getWorksheetpagination().getPageSize();
        return ((int) all / pagesize) + 1;
    }
    public PaginationHelper getWorksheetpagination() {
        if (worksheetpagination == null) {
            worksheetpagination = new PaginationHelper(20) {

                @Override
                public int getItemsCount() {
                    return getEditngcontrolData().size();
                }

                @Override
                public DataModel createPageDataModel() {
                    fc.print("PageFirst : " + getPageFirstItem());
                    fc.print("PageLase : " + getPageLastItem());
                    ListDataModel listmodel;
                    if (getEditngcontrolData().size() > 0) {
                        listmodel = new ListDataModel(getEditngcontrolData().subList(getPageFirstItem(), getPageLastItem() + 1));
                    } else {
                        listmodel = new ListDataModel(getEditngcontrolData());
                    }
                    return listmodel;
                }
            };
        }
        return worksheetpagination;
    }
    
    private void loadItemNgType() {
        getItemNgType().add(new SelectItem("","--- Select one ----"));
        getItemNgType().add(new SelectItem("consider","    Consider      "));
        getItemNgType().add(new SelectItem("ng","    Ng      "));
        getItemNgType().add(new SelectItem("repair","    Repair      "));
       
    }
    private void loadItemNgStatus() {
        getItemNgStatus().add(new SelectItem("","--- Select one ----"));
        getItemNgStatus().add(new SelectItem("Active","    Active         "));
        getItemNgStatus().add(new SelectItem("Inactive","    Inactive       ")); 
    }
    public void ChangeValueNgStatus(ValueChangeEvent event)
    {
        ngStatusSearch  = (String) event.getNewValue();
        fc.print("ngNameSearch"+ngNameSearch);
    }
    public void ChangeValueNgType(ValueChangeEvent event)
    {
        ngTypeSearch  = (String) event.getNewValue();
        fc.print("ngTypeSearch"+ngTypeSearch);
    }
    
    public void setEditngcontrolData(List<editngDetail> editngcontrolData) {
        this.editngcontrolData = editngcontrolData;
    }

    public void searchEditngList() { 
        currentPool  = null; 
        worksheetpagination = null;
        if(ngNameSearch != null && !ngNameSearch.trim().isEmpty())
        {
            searchByNgName(); 
            fc.print("ngNameSearch"+ngNameSearch);
        }
        else if(ngCodeSearch != null && !ngCodeSearch.trim().isEmpty())
        {
            searchByNgCode();
            fc.print("ngCodeSearch");
        }
        else if(ngTypeSearch != null && !ngTypeSearch.trim().isEmpty())
        {
            searchByNgType();
            fc.print("ngTypeSearch"+ngTypeSearch);
        }
        else if(ngStatusSearch != null && !ngStatusSearch.trim().isEmpty())
        {
            searchByNgStatus();
            fc.print("ngStatusSearch"+ngStatusSearch);
        }
        else
        {
            loadSearchEditListAll();
        }
       
    }
    public void resetData()
    {
        ngNameSearch  = null;
        ngTypeSearch  = null;
        ngTypeSearch  = null;
        ngStatusSearch = null;
    }  
    public void  searchByNgName()
    {
//       editngcontrolData  = null;
//       itemPc2ng  = null;
      try{
       fc.print("testsearch"); 
       //editngcontrolData  = new ArrayList<editngDetail>();  
       editngcontrolData  = null;
       itemPc2ng  = null;
       itemPc2ng  = getNgPoolJpaController().findByNgNameList(ngNameSearch);
       if(itemPc2ng.isEmpty())
       {
           fc.print("null");
       }
       for(NgPool itempc2ndg : itemPc2ng)
         {   

src/java/com/setting/model/Data/ModelListData.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.setting.model.Data;

/**
 *
 * Machine User @author pang
 * Development by Chusak laojang
 * Date : Oct 24, 2012, Time : 3:11:35 PM 
 * Copy Right 4 Xtreme Co.,Ltd.
 */
public class ModelListData {
    private String index;
    private String modelGroup;
    private String modelType;
    private String modelSeries;
    private String modelName;
    private String status;
    private String lock;
    private String edit; 
    public ModelListData(String index, String modelGroup, String modelType, String modelSeries, String modelName, String status, String lock, String edit) {
        this.index = index;
        this.modelGroup = modelGroup;
        this.modelType = modelType;
        this.modelSeries = modelSeries;
        this.modelName = modelName;
        this.status = status;
        this.lock = lock;
        this.edit = edit;
    } 
    public String getEdit() {
        return edit;
    }

    public void setEdit(String edit) {
        this.edit = edit;
    }

    public String getIndex() {
        return index;
    }

    public void setIndex(String index) {
        this.index = index;
    }

    public String getLock() {
        return lock;
    }

    public void setLock(String lock) {
        this.lock = lock;
    }

    public String getModelGroup() {
        return modelGroup;
    }

    public void setModelGroup(String modelGroup) {
        this.modelGroup = modelGroup;
    }

    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getModelSeries() {
        return modelSeries;
    }

    public void setModelSeries(String modelSeries) {
        this.modelSeries = modelSeries;
    }

    public String getModelType() {
        return modelType;
    }

    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    } 
}

src/java/com/setting/menu/TreeBean.java
package com.setting.menu;

import com.icesoft.faces.component.tree.IceUserObject; 
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * <p>
 * A basic backing bean for a ice:tree component.  The only instance variable
 * needed is a DefaultTreeModel Object which is bound to the icefaces tree
 * component in the jspx code.</p>
 * <p>
 * The tree created by this backing bean is very simple, containing only text
 * nodes.  The plus and minus icons which expand the tree are rendered because
 * of attributes set at the component level.
 * </p>
 *
 */
public class TreeBean {

    // tree default model, used as a value for the tree component
    private DefaultTreeModel model;
    private DefaultMutableTreeNode addMenu(String name,String action,boolean leaf){
          DefaultMutableTreeNode branchNode = new DefaultMutableTreeNode();
            IceUserObject branchObject = new IceUserObject(branchNode);
            branchObject.setText(name);
            branchObject.setTooltip(action);
            branchNode.setUserObject(branchObject);
            branchObject.setLeaf(leaf);
        return branchNode;
    }
    public TreeBean(){
        // create root node with its children expanded
        DefaultMutableTreeNode rootTreeNode = new DefaultMutableTreeNode();
        IceUserObject rootObject = new IceUserObject(rootTreeNode);
        rootObject.setText("Main Menu");
        rootObject.setExpanded(false);
        rootTreeNode.setUserObject(rootObject);
         
        // model is accessed by by the ice:tree component
            model =  new DefaultTreeModel(rootTreeNode);
            DefaultMutableTreeNode frontNode = addMenu("Module Front line", "",false);
            frontNode.add(addMenu("Front line","worksheetlist",true));
            rootTreeNode.add(frontNode);
            DefaultMutableTreeNode backNode = addMenu("Module Back line", "",false);
            // <f:param name="myParam" value="createAutoWorksheet">Create Auto worksheet</f:param>  
            backNode.add(addMenu("Create Assy worksheet","createAssyWorksheet",true));
            // <f:param name="myParam" value="assyWoeksheetList">Assy worksheet list</f:param>  
            backNode.add(addMenu("Assy worksheet list","assyWoeksheetList",true));
            //  <f:param name="myParam" value="createAutoWorksheet">Create Auto worksheet</f:param>  
            backNode.add(addMenu("Create Auto worksheet","createAutoWorksheet",true));
            //  <f:param name="myParam" value="autoworksheetList">Auto worksheet list</f:param>  
            backNode.add(addMenu("Auto worksheet list","autoworksheetList",true)); 
            //  <f:param name="myParam" value="createLineworksheet">Create line worksheet</f:param>  
            backNode.add(addMenu("Create line worksheet","createLineworksheet",true));
            //  <f:param name="myParam" value="lineWorksheetList">Line worksheet list</f:param>  
            backNode.add(addMenu("Line worksheet list","lineWorksheetList",true)); 
            //  <f:param name="myParam" value="createpacking">Create Packing</f:param>  
            backNode.add(addMenu("Create Packing","createpacking",true));
            //  <f:param name="myParam" value="packing">Packing</f:param>  
            backNode.add(addMenu("Packing","packing",true));
            //  <f:param name="myParam" value="refu">Refu</f:param> 
            backNode.add(addMenu("Refu","refu",true));
            //  <f:param name="myParam" value="refulist">Refu List</f:param>  
            backNode.add(addMenu("Refu List","refulist",true));
            //  <f:param name="myParam" value="pcb">PCB</f:param>  
            backNode.add(addMenu("PCB","pcb",true));
            //  <f:param name="myParam" value="pcblist">PCB List</f:param>  
            backNode.add(addMenu("PCB List","pcblist",true));
            rootTreeNode.add(backNode);  
           
            DefaultMutableTreeNode reportNode = addMenu("Report", "",false);
            reportNode.add(addMenu("Report List","reportList",true));
            reportNode.add(addMenu("R Chart","rChart",true));
            rootTreeNode.add(reportNode);
            
            DefaultMutableTreeNode settingNode = addMenu("Setting", "",false);
            settingNode.add(addMenu("Edit model step","editModelStep",true));
            settingNode.add(addMenu("R Chart","rChart",true));
            settingNode.add(addMenu("Data process","dataProcess",true));
            settingNode.add(addMenu("Edit NG","editNG",true));
            settingNode.add(addMenu("Select barcode type","selectBarcodeType",true));
            rootTreeNode.add(settingNode);
            
            DefaultMutableTreeNode machineNode = addMenu("Machine", "",false);
            machineNode.add(addMenu("M/C#","mc",true));
            machineNode.add(addMenu("M/C# Performance","mcPerformance",true));
            rootTreeNode.add(machineNode);
            
            DefaultMutableTreeNode configNode = addMenu("App Config", "",false);
            configNode.add(addMenu("Create user","createUser",true));
            configNode.add(addMenu("User config","userConfig",true));
            configNode.add(addMenu("Role","role",true));
            rootTreeNode.add(configNode);

    }

    /**
     * Gets the tree's default model.
     *
     * @return tree model.
     */
    public DefaultTreeModel getModel() {
        return model;
    }

}

web/pages/setting/stdtimesetting/listview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:icecore="http://www.icefaces.org/icefaces/core"
      xmlns:ace="http://www.icefaces.org/icefaces/components"
      xmlns:ice="http://www.icesoft.com/icefaces/component">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>  
            <!--Create Worksheet-->
            <div class="box">
                <div class="heading">
                    <h1> <img src="../images/h1_stdtime.png" />STD Time Setting  </h1>
                    <div class="buttons">
                        
                        <ice:panelTab rendered="#{stdtimesettingcontrol.statusAddButton}" >    
                            <ice:commandButton value="Add" styleClass="button_create" actionListener="#{stdtimesettingcontrol.changeToAdd}" />
                        </ice:panelTab>
                        <ice:panelTab rendered="#{stdtimesettingcontrol.statusSaveButton}" >
                            <ice:commandButton value="Save" styleClass="button_save" actionListener="#{stdtimesettingcontrol.changeToSave}"/>
                            &nbsp;
                            <ice:commandButton value="Cancel" styleClass="button_cancel" actionListener="#{stdtimesettingcontrol.changeToCancel}" />
                        </ice:panelTab>
                    </div>
                </div>
                <div class="content">
                    <table class="form">
                        <tr>
                            <td class="label">Header name :</td>
                            <td >
                                <ice:inputText value="#{stdtimesettingcontrol.currentStdTime.headerName}"/>
                                &nbsp;
                                <ice:outputText style="color: red;" value="#{stdtimesettingcontrol.validateHeaderName}" />
                            </td>
                            <td class="label">Hours :</td>
                            <td>
                                <ice:inputText value="#{stdtimesettingcontrol.currentStdTime.hours}" />
                                &nbsp;
                                <ice:outputText style="color: red;" value="#{stdtimesettingcontrol.validateHours}" />
                            </td>
                            <td class="label">Minute:</td>
                            <td>
                                <ice:inputText  value="#{stdtimesettingcontrol.currentStdTime.minute}"/>
                                &nbsp;
                                <ice:outputText style="color: red;" value="#{stdtimesettingcontrol.validateMinutes}" />
                            </td>
                        </tr>
                    </table> 
                    <ice:dataTable width="100%" value="#{stdtimesettingcontrol.itemStdTime}" var="itemStdTime" > 
                        <ice:column style="width: 5%;">
                            <f:facet name="header">
                                <ice:outputText value="No." />
                            </f:facet>  
                            <ice:outputText value="#{itemStdTime.number}" />
                        </ice:column>
                        <ice:column style="width: 30%;">
                            <f:facet name="header">
                                <ice:outputText value="Header name" />
                            </f:facet>
                            <ice:outputText value="#{itemStdTime.headerName}" /> 
                        </ice:column>
                        <ice:column style="width: 15%;">
                            <f:facet name="header">
                                <ice:outputText value="Hours" />
                            </f:facet>
                            <ice:outputText value="#{itemStdTime.hours}" />
                        </ice:column>
                        <ice:column style="width: 15%;">
                            <f:facet name="header">
                                <ice:outputText value="Minute" />
                            </f:facet>
                            <ice:outputText value="#{itemStdTime.minute}" />
                        </ice:column>
                        <ice:column style="width: 20%;">
                            <f:facet name="header">
                                <ice:outputText value="DataCreate" />
                            </f:facet>
                            <ice:outputText value="#{itemStdTime.date}" />
                        </ice:column>
                        <ice:column style="width: 15%;">
                            <f:facet name="header">
                                <ice:outputText value="Action" />
                            </f:facet>
                            <ice:commandButton value="Edit" styleClass="button_edit" actionListener="#{stdtimesettingcontrol.changeToEdit(itemStdTime.index)}" />
                            <ice:commandButton panelConfirmation="delStdSetting" value="Delete" styleClass="button_del"  actionListener="#{stdtimesettingcontrol.changeToDelete(itemStdTime.index)}"/>
                            <ice:panelConfirmation id="delStdSetting" acceptLabel="Confirm" cancelLabel="Cancel"  title="Confirm to delete STD settingtime" message="You are about to STD Time Setting. Are you sure?" draggable="false" autoCentre="true" rendered="true"/>
                        </ice:column>
                    </ice:dataTable> 
                </div>
            </div>  
<!--            <br/>
            <ice:commandButton value="Test" actionListener="#{stdtimesettingcontrol.changeToTest()}" styleClass="button_edit"/>
            <ice:inputText value="#{stdtimesettingcontrol.testinput}"/>
            <br/>
            <ice:commandButton value="edit" styleClass="button_edit" actionListener="#{stdtimesettingcontrol.editTest()}" />
            <br/>
            <ice:outputText value="#{stdtimesettingcontrol.indexEdit}" />
            <br/>
            <ice:commandButton value="show data " actionListener="#{stdtimesettingcontrol.showListData()}" />
            <BR/>
            <ice:dataTable value="#{stdtimesettingcontrol.masterModel}" var="itemList" >
                <ice:column>
                    <f:facet name="header">
                        <ice:outputText value="show" />
                    </f:facet>
                    <ice:outputText value="#{itemList.headerName}" />
                </ice:column>
            </ice:dataTable>
             <div class="pagination">
                        <div align="center"> 
                            <ice:commandLink styleClass="prev" actionListener="#{stdtimesettingcontrol.previous}" value="Previous" rendered="#{stdtimesettingcontrol.worksheetpagination.hasPreviousPage}"/> 
                            #{stdtimesettingcontrol.worksheetpagination.page+1}/#{stdtimesettingcontrol.allPages}
                            <ice:commandLink styleClass="next" actionListener="#{stdtimesettingcontrol.next}" value="Next" rendered="#{stdtimesettingcontrol.worksheetpagination.hasNextPage}"/>
                            <div class="results">
                                Showing #{stdtimesettingcontrol.worksheetpagination.pageFirstItem+1} to #{stdtimesettingcontrol.worksheetpagination.pageLastItem+1} of #{stdtimesettingcontrol.worksheetpagination.itemsCount}
                            </div>
                        </div>
                    </div>  
            <br/>
            <ice:commandButton value="show pop up"  actionListener="#{stdtimesettingcontrol.showPopup()}"/>
            <ice:panelPopup   rendered="#{stdtimesettingcontrol.showPopup}" modal="true"  >
                <f:facet name="header">
                   <ice:commandButton value="close pop up"  actionListener="#{stdtimesettingcontrol.closePopup()}"/>
                </f:facet>    
                <f:facet name="body">
                     <ice:dataTable value="#{stdtimesettingcontrol.masterModel}" var="itemList" >
                <ice:column>
                    <f:facet name="header">
                        <ice:outputText value="show" />
                    </f:facet>
                    <ice:outputText value="#{itemList.headerName}" />
                </ice:column>
            </ice:dataTable>
             <div class="pagination">
                        <div align="center"> 
                            <ice:commandLink styleClass="prev" actionListener="#{stdtimesettingcontrol.previous}" value="Previous" rendered="#{stdtimesettingcontrol.worksheetpagination.hasPreviousPage}"/> 
                            #{stdtimesettingcontrol.worksheetpagination.page+1}/#{stdtimesettingcontrol.allPages}
                            <ice:commandLink styleClass="next" actionListener="#{stdtimesettingcontrol.next}" value="Next" rendered="#{stdtimesettingcontrol.worksheetpagination.hasNextPage}"/>
                            <div class="results">
                                Showing #{stdtimesettingcontrol.worksheetpagination.pageFirstItem+1} to #{stdtimesettingcontrol.worksheetpagination.pageLastItem+1} of #{stdtimesettingcontrol.worksheetpagination.itemsCount}
                            </div>
                        </div>
                    </div>   
                </f:facet>     
            </ice:panelPopup>
            
            -->
        </h:form>
    </h:body>
</html>